# Generated by Django 5.2.9 on 2025-12-23 22:10

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa Firmy')),
                ('nip', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIP')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Baza Firm',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Stanowisko')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='offers.company', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Klient / Kontakt',
                'verbose_name_plural': 'Baza Klientów',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_number', models.CharField(max_length=50, unique=True, verbose_name='Numer oferty')),
                ('status', models.CharField(choices=[('draft', 'Robocza'), ('pending', 'Oczekuje na akceptację'), ('consultation', 'Konsultacja z Seniorem'), ('approved', 'Zatwierdzona'), ('sent', 'Wysłana'), ('rejected', 'Odrzucona')], default='draft', max_length=20, verbose_name='Status')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Wstęp/Opis oferty', null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Suma PLN')),
                ('currency_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=6, verbose_name='Kurs EUR (dla informacji)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validity_days', models.PositiveIntegerField(default=14, verbose_name='Ważność oferty (dni)')),
                ('payment_deadline_days', models.PositiveIntegerField(default=7, verbose_name='Termin płatności (dni)')),
                ('payment_method', models.CharField(choices=[('transfer', 'Przelew tradycyjny'), ('split', 'Przelew (Split Payment)'), ('cash', 'Gotówka'), ('card', 'Karta płatnicza')], default='transfer', max_length=20, verbose_name='Metoda płatności')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Powód odrzucenia (CEO)')),
                ('external_file', models.FileField(blank=True, null=True, upload_to='offers_archive/', verbose_name='Archiwalny PDF')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.client', verbose_name='Klient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Nazwa produktu')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ilość')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena jedn. PLN')),
                ('price_in_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena katalogowa EUR')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='offers.offer')),
            ],
        ),
    ]
