# Generated by Django 5.2.8 on 2025-12-10 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer_numer',
            new_name='offer_number',
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Nazwa Usługi/Produktu')),
                ('quantity', models.PositiveBigIntegerField(default=1, verbose_name='Ilość')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena jedn.')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='offers.offer')),
            ],
        ),
    ]
