# Generated by Django 5.2.9 on 2025-12-27 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offer_options_offer_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa Naszej Firmy')),
                ('nip', models.CharField(max_length=20, verbose_name='NIP')),
                ('address', models.TextField(verbose_name='Adres')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email kontaktowy')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Konto Bankowe')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Wystawca (Nasza Firma)',
                'verbose_name_plural': 'Konfiguracja Wystawców',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='offers.seller', verbose_name='Wystawca'),
        ),
    ]
