# Generated by Django 5.2.8 on 2025-12-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_rename_offer_numer_offer_offer_number_offeritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Wersja Robocza'), ('sent', 'Wysłana'), ('accepted', 'Zaakceptowana'), ('rejected', 'Odrzucona')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
