# Generated by Django 5.2.8 on 2025-12-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_status_alter_offer_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Ilość'),
        ),
    ]
