# Generated by Django 5.2.9 on 2025-12-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_seller_offer_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Nazwa Firmy', 'verbose_name_plural': 'Nasze Firmy'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Robocza'), ('pending', 'Oczekuje na akceptację'), ('consultation', 'Konsultacja'), ('approved', 'Zatwierdzona'), ('sent', 'Wysłana'), ('rejected', 'Odrzucona')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
