# Generated by Django 5.2.8 on 2025-12-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offeritem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='client_email',
            field=models.EmailField(max_length=254, verbose_name='Email klienta'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis ogólny'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Numer oferty'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Wersja Robocza'), ('sent', 'Wysłana'), ('accepted', 'Zaakceptowana'), ('rejected', 'Odrzucona')], default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena całkowita'),
        ),
    ]
