# Generated by Django 5.2.9 on 2025-12-11 20:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_offer_client_email_alter_offer_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Opis oferty widoczny na PDF', null=True),
        ),
    ]
