# Generated by Django 5.2.9 on 2025-12-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_offer_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-id'], 'verbose_name': 'Oferta', 'verbose_name_plural': 'Oferty'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Robocza'), ('pending', 'Oczekuje na akceptację'), ('approved', 'Zatwierdzona'), ('sent', 'Wysłana')], default='draft', max_length=10, verbose_name='Status'),
        ),
    ]
