# Generated by Django 5.2.9 on 2025-12-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_alter_offer_options_alter_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='external_file',
            field=models.FileField(blank=True, null=True, upload_to='offers_archive/', verbose_name='Wgrany plik PDF (dla starych ofert)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Robocza'), ('pending', 'Oczekuje na akceptację'), ('approved', 'Zatwierdzona'), ('sent', 'Wysłana'), ('rejected', 'Odrzucona')], default='draft', max_length=10, verbose_name='Status'),
        ),
    ]
